version: "3"

services:

  bookstore_db:
    container_name: bookstore_db
    image: 'mongo'
    ports:
      - "2702:27017"
    volumes:
      - ./mongo/:/data/db
    env_file:
      - .env

  bookstore:
    container_name: bookstore
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - bookstore_db
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env

volumes:  
  mongo: {}